### PR TITLE
make public_ip work for any case 'none' at 'instance_access_configs_for'

### PR DESCRIPTION
**Pull request by abhishekkr**
version in use: knife-google (2.0.0)

Running `knife google server create ...--gce-public-ip none` command still attached Ephemeral(default) public-ip to the new node. 
Making match non-case-sensitive at 'google_service.rb:instance_access_configs_for' fixed it.

Here is the PR for it, also made it similar to 'valid_public_ip_setting?' handling of case.

### CODE REVIEW

**Comment by abhishekkr** [comment]
the error check is for Ruby 2.0.0
```
An error occurred while installing chef-zero (4.6.2), and Bundler cannot
```

**Comment by abhishekkr** [comment]
to re-run Travis

**Comment by hrez** [comment]
Thanks for the fix. Why isn't it still merged to the master? It's obviously a bug.

**Comment by jjasghar** [comment]
@abhishekkr can you rebase off master please?

**Comment by jjasghar** [comment]
With our new policy please use the [DCO signing process](https://discourse.chef.io/t/a-developer-certificate-of-origin-dco-is-now-required-with-code-contributions/9579).

For a [detailed description](http://stackoverflow.com/questions/13457203/how-to-add-the-signed-off-by-field-in-the-git-patch) or you can just do:

```
$ git commit -s
$ #Or
$ git commit --signoff
```

If you already have the commit, use git commit --amend or git rebase -i to edit your commit message, and add the above signoff line.

Or if you want a more perminant option the following is a way to set it forever:

```bash
$ git config commit.gpgsign true
```

**Comment by abhishekkr** [comment]
@jjasghar had already pushed required diffs before, so pushed in an empty commit signed

**Comment by abhishekkr** [comment]
@jjasghar do I need to do anything else

**Comment by jjasghar** [comment]
I'll be releasing a new version of the gem soon.

**Comment by jjasghar** [comment]
I have released v3.1.0

**Pull request merged**
