### PR TITLE
fix for undefined method 'snake_case'

### PR DESCRIPTION
**Pull request by paulrossman**
For issue #44. Compatible with latest 'google-api-client' that requires 'extlib'. Fixes 'snake_case'.

### CODE REVIEW

**Comment by erjohnso** [comment]
Thanks @paulrossman!

**Comment by mansona** [comment]
Hey has this been released yet? I'm still getting this error with a fresh install of knife-google

**Comment by paulrossman** [comment]
It's not been released via Rubygems yet. In the meantime, add this to your
Gemfile:


*gem 'knife-google', '>= 1.3.2', :github => 'chef/knife-google'*

and exec knife with:

*bundle exec knife google*

**Comment by zhunpingzhangsc** [comment]
@paulmooring thanks, I tried it but it says:

$ bundle exec knife google 
The git source git://github.com/chef/knife-google.git is not yet checked out. Please run `bundle install` before trying to start your application
$ bundle install
Updating git://github.com/chef/knife-google.git
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Could not find gem 'knife-google (>= 1.3.2) ruby' in git://github.com/chef/knife-google.git (at master).
Source contains 'knife-google' at: 1.3.1

any ideas?

**Comment by zhunpingzhangsc** [comment]
downloaded knife-google from github, compile & install problem solved

**Comment by ohadpartuck** [comment]
This solution worked for me. but,
@paulrossman when will it be released to RubyGems?

**Comment by samirahmedsc** [comment]
does anybody at chef even care about this ... its been a year and 1.3.2 still hasn't been released...

**Comment by paulrossman** [comment]
We have an [major update](https://github.com/paulrossman/knife-google/tree/google-api-ruby-client) that we are moving forward with. We will for certain release a new gem after this update has been merged.

**Comment by samirahmedsc** [comment]
that is awesome! I have built 2.0.0 from master and it works well ... can't
wait for the easy gem install

**Pull request merged**
